{% set name = "schedula" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vinci1it2000/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: ddf2ca94617be5224a7e0971037dcfba7020680262383e766ef2a764a19e1bbc
    folder: dist
  - url: https://github.com/vinci1it2000/schedula/archive/v{{ version }}.tar.gz
    sha256: ddf2ca94617be5224a7e0971037dcfba7020680262383e766ef2a764a19e1bbc
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - beautifulsoup4
    - dill
    - docutils
    - flask
    - jinja2
    - lxml
    - multiprocess
    - nose
    - pip
    - pygments
    - python >=3.6
    - python-graphviz
    - regex
    - requests
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
  run:
    - python >=3.6

test:
  source_files:
    - src/tests/test_dispatcher.py
    - src/tests/utils
    - src/setup.cfg
  requires:
    - nose
    - docutils
    - beautifulsoup4
    - dill
    - flask
    - jinja2
    - lxml
    - multiprocess
    - nose
    - pip
    - pygments
    - python-graphviz <0.10.1
    - regex
    - requests
  imports:
    - schedula
  commands:
    - python -m pip check
    - cd src && nosetests -e "test_errors"

about:
  home: https://github.com/vinci1it2000/schedula
  license: EUPL-1.1
  license_family: OTHER
  license_file: dist/LICENSE.txt
  summary: An intelligent function scheduler, which selects and executes functions.
  doc_url: https://schedula.readthedocs.io/en/v{{ version }}
  doc_source_url: https://github.com/vinci1it2000/schedula/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - bollwyvl
