{% set version = "1.4.0" %}

package:
  name: schedula
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/schedula/schedula-{{ version }}.tar.gz
    sha256: e5d7bef9be6c050d514efdde800fc503c1307bdbbcac2670786eeae54e28b7df
    folder: dist
  - url: https://github.com/vinci1it2000/schedula/archive/v{{ version }}.tar.gz
    sha256: 06cf5a44188cdac7efa6085f6a8a6d8ba3b0607ca19857bad2e481b2223a5df5
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - src/examples
    - src/tests/test_dispatcher.py
    - src/tests/test_import.py
    - src/tests/utils
    - src/setup.cfg
  requires:
    - beautifulsoup4
    - ddt
    - dill
    - docutils
    - flask
    - jinja2
    - lxml
    - multiprocess
    - nose
    - pip
    - pygments
    - python-graphviz
    - regex
    - requests
  imports:
    - schedula
  commands:
    - pip check
    - cd src && nosetests -e "test_(errors|long_path|view|plot)"

about:
  home: https://github.com/vinci1it2000/schedula
  license: EUPL-1.1
  license_family: OTHER
  license_file: src/LICENSE.txt
  summary: An intelligent function scheduler, which selects and executes functions.
  doc_url: https://schedula.readthedocs.io/en/v{{ version }}
  doc_source_url: https://github.com/vinci1it2000/schedula/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - bollwyvl
