{% set version = "1.4.1" %}

package:
  name: schedula
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/schedula/schedula-{{ version }}.tar.gz
    sha256: c765c689ca1614d798270c2419e2c8aedb80445785a62427c014d9a0a859f61f
    folder: dist
  - url: https://github.com/vinci1it2000/schedula/archive/v{{ version }}.tar.gz
    sha256: 68029bd7fe790cc8d688fb6a7721dd8ac34bfaf13f1c871f73a89629124320ce
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - src/examples
    - src/tests/test_dispatcher.py
    - src/tests/test_import.py
    - src/tests/utils
    - src/setup.cfg
  requires:
    - beautifulsoup4
    - ddt
    - dill
    - docutils
    - flask
    - jinja2
    - lxml
    - multiprocess
    - nose
    - pip
    - pygments
    - python-graphviz
    - regex
    - requests
  imports:
    - schedula
  commands:
    - pip check
    - cd src && nosetests -e "test_(errors|long_path|view|plot|form|map_dispatch)"

about:
  home: https://github.com/vinci1it2000/schedula
  license: EUPL-1.1
  license_family: OTHER
  license_file: src/LICENSE.txt
  summary: An intelligent function scheduler, which selects and executes functions.
  doc_url: https://schedula.readthedocs.io/en/v{{ version }}
  doc_source_url: https://github.com/vinci1it2000/schedula/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - bollwyvl
