{% set version = "1.2.9" %}

package:
  name: schedula
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/schedula/schedula-{{ version }}.tar.gz
    sha256: d6ac0d5d5e9b358e8a1e2ea55d38154f24ecb01469ab27d81250b47ce33e2e05
    folder: dist
  - url: https://github.com/vinci1it2000/schedula/archive/v{{ version }}.tar.gz
    sha256: dced032826d6979851d60c06022dae90e723ee5b782ce71d44f1dc6c53f57dbe
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - src/tests/test_dispatcher.py
    - src/tests/utils
    - src/setup.cfg
  requires:
    - nose
    - docutils
    - beautifulsoup4
    - dill
    - flask
    - jinja2
    - lxml
    - multiprocess
    - nose
    - pip
    - pygments
    - python-graphviz
    - regex
    - requests
  imports:
    - schedula
  commands:
    - pip check
    - cd src && nosetests -e "test_(errors|long_path|view)"

about:
  home: https://github.com/vinci1it2000/schedula
  license: EUPL-1.1
  license_family: OTHER
  license_file: src/LICENSE.txt
  summary: An intelligent function scheduler, which selects and executes functions.
  doc_url: https://schedula.readthedocs.io/en/v{{ version }}
  doc_source_url: https://github.com/vinci1it2000/schedula/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - bollwyvl
