{% set version = "1.3.0" %}

package:
  name: schedula
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/schedula/schedula-{{ version }}.tar.gz
    sha256: e2b85965e399c6f3d367ba430d0cf1a6f9c750ca0e810d21acb66b703f54fb96
    folder: dist
  - url: https://github.com/vinci1it2000/schedula/archive/v{{ version }}.tar.gz
    sha256: b7a572cd518de8fddfb8adb5829188b7fb74b700b9005c7a2722d7963a23e152
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - src/tests/test_dispatcher.py
    - src/tests/utils
    - src/setup.cfg
  requires:
    - nose
    - docutils
    - beautifulsoup4
    - dill
    - flask
    - jinja2
    - lxml
    - multiprocess
    - nose
    - pip
    - pygments
    - python-graphviz
    - regex
    - requests
  imports:
    - schedula
  commands:
    - pip check
    - cd src && nosetests -e "test_(errors|long_path|view|plot)"

about:
  home: https://github.com/vinci1it2000/schedula
  license: EUPL-1.1
  license_family: OTHER
  license_file: src/LICENSE.txt
  summary: An intelligent function scheduler, which selects and executes functions.
  doc_url: https://schedula.readthedocs.io/en/v{{ version }}
  doc_source_url: https://github.com/vinci1it2000/schedula/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - bollwyvl
