{% set name = "schedula" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vinci1it2000/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8c8858db876bec3127bb5f61895fc8b308f7e868c336a15e18aa50dd731de8bb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - beautifulsoup4
    - dill
    - docutils
    - flask
    - jinja2
    - lxml
    - multiprocess
    - networkx >=2.0.0
    - nose
    - pip
    - pygments
    - python >=3
    - python-graphviz
    - regex
    - requests
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
  run:
    - dill
    - networkx >=2.0.0,<2.4
    - python

test:
  source_files:
    - test/test_dispatcher.py
    - test/utils
    - setup.cfg
  requires:
    - nose
    - docutils
    - beautifulsoup4
    - dill
    - flask
    - jinja2
    - lxml
    - multiprocess
    - networkx >=2.0.0
    - nose
    - pip
    - pygments
    - python >=3
    - python-graphviz <0.10.1
    - regex
    - requests
  imports:
    - schedula
  commands:
    - nosetests

about:
  home: https://github.com/vinci1it2000/schedula
  license: EUPL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: 'An intelligent function scheduler, which selects and executes functions.'
  doc_url: https://schedula.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
