{% set version = "1.2.16" %}

package:
  name: schedula
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/schedula/schedula-{{ version }}.tar.gz
    sha256: 049aa762533c9afca5c07d7c30bd683362e91506a0b228c7fb11527f0201aa4e
    folder: dist
  - url: https://github.com/vinci1it2000/schedula/archive/v{{ version }}.tar.gz
    sha256: 1cdb0a6c9a90c620de8ea57e66d98318ae1ea16f7ed0e09f17cc6ead37142bb0
    folder: src

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - src/tests/test_dispatcher.py
    - src/tests/utils
    - src/setup.cfg
  requires:
    - nose
    - docutils
    - beautifulsoup4
    - dill
    - flask
    - jinja2
    - lxml
    - multiprocess
    - nose
    - pip
    - pygments
    - python-graphviz
    - regex
    - requests
  imports:
    - schedula
  commands:
    - pip check
    - cd src && nosetests -e "test_(errors|long_path|view|plot)"

about:
  home: https://github.com/vinci1it2000/schedula
  license: EUPL-1.1
  license_family: OTHER
  license_file: src/LICENSE.txt
  summary: An intelligent function scheduler, which selects and executes functions.
  doc_url: https://schedula.readthedocs.io/en/v{{ version }}
  doc_source_url: https://github.com/vinci1it2000/schedula/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - bollwyvl
