travis:
  secure:
    BINSTAR_TOKEN: Um7PAccZVP6CijSNlBMEhnchh5q3kmGQISzIEWQWjIz1B/rASaVU+gdHRRe+SFJVILOnQdoR+E614DbArknBJJbva6Iniz+W/RfU7AKjbwu4zkNSs2YY9Ny1sTHnMPlMSZ53sbmQUBTlATfSU5/jzAWW8j0Jt5veSW3YEw1+6PhuGS/WopHqRt55ntDoTWjAzyDKH6PXAN45UxIsQ5NwfnfxnB2VGMvNWTGpFUeUB9Y0vuVyfRvBRapS3Ie1siW3WxsdyPO2XhK9Q0CIYfG79ainvXNJAyY//41cD5ruaxxOTh6hIU6CEUxxFjXPqDZ3S++OiNyhRq9iw560//GVkbIcwvqiBe7dxJ8L27H/C9HgIB7KH1oCoahS/bNNM3HJHhFIIooHZgbFTSlCtwBUALN8y1k5AyBsz7yQXBfQ/chuAyV/8Rm3tY4IUq/CmsAbhVwN9jVQiApcW43RvEUzSqHHy7GTaZwAeMZaTKAeKXkuILHD2+cS+S8OlmdDFNQYBTUGOUZp4LDeDpOTifgVLS1L0eTer+OlXn/IBSHUUqZoC/CXNLslTabtQMnUaxcyKdNRz5KEV1Dg2ELSlOzymILezp7dbIWDw7yIIzbj+Vkrvkcdg820mIObKHXGt/ahim/zSZ6giO7xhYvaElqeb3JUM7pEY7JHb1+/RNpre0c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
